default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  port: 5432
  username: postgres
  password: postgres

development:
  <<: *default
  database: blog_app_development

test:
  <<: *default
  database: blog_app_test